# Generated by Django 6.0.4 on 2026-05-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
